# Generated by Django 4.1.3 on 2022-11-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborator',
            name='description',
            field=models.TextField(verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='colaborator',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
