# Generated by Django 4.1.3 on 2022-11-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborators', '0002_alter_colaborator_description_alter_colaborator_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborator',
            options={'ordering': ['name'], 'verbose_name': 'profesional', 'verbose_name_plural': 'profesionales'},
        ),
    ]
